import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { HeaderProvider } from '@/features/@shared/context/HeaderContext';
import { SpinnerProvider } from '@/features/@shared/context/SpinnerContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // pilih sesuai kebutuhan
  variable: '--font-poppins', // optional, untuk dipakai di Tailwind
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} text-black antialiased`}>
        <HeaderProvider>
          <SpinnerProvider>{children}</SpinnerProvider>
        </HeaderProvider>
      </body>
    </html>
  );
}
